apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  NODE_ENV: "development"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "taskmanager" 
  DB_USERNAME: "postgres"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"